### ISSUE TITLE
Incongruence between Flow cytometry data and Smudgplot

### ISSUE THREAD

**Issue by vincianem** [KamilSJaron/smudgeplot#183]
Good afternoon,

Thanks a lot for this wonderful tool which is Smudgeplot!

I am trying to infer the ploidy of _Salix_ (willows) species. _Salix_ genomes are about 300 Mb for diploids. Among my samples are diploids, tetraploids and hexaploids. I have flow cytometry data for 2/3 of the samples among which are three individuals of _S. caesia_. 

_S. caesia_ individuals were proposed as tetraploid by Smudgplot expect one proposed as diploid. I would be grateful if you may help me to figure out why the last is given as diploid.

**smudgeplot**

Here are the commands I used to generate the smudgplot: 
`indir=/proj/naiss2023-6-57/1-trim_seq/bgi2024
sample=26M1
n=8
FastK -v -t4 -k40 -M51 -T$n $indir/$sample.R[12].clean.fastq -N$sample.FastK_Table
smudgeplot.py hetmers -L 30 -t $n -o $sample.kmerpairs --verbose $sample.FastK_Table
smudgeplot.py plot -o $sample.trial_run $sample.kmerpairs_text.smuShow` 

Here is the plot:
[26M1.trial_run_smudgeplot_log10.pdf](https://github.com/user-attachments/files/18113181/26M1.trial_run_smudgeplot_log10.pdf)

I also attached the warnings produced by Smudgplot.
[26M1.trial_run_warnings.txt](https://github.com/user-attachments/files/18113206/26M1.trial_run_warnings.txt)

**Comment by KamilSJaron** [comment]
Hi, @vincianem on the same day you had a problem with not getting .smu files - is that one resolved?

This plot you posted has some legacy problems we have fixed in the latest smudgeplot version - namely, your data are not very high in coverage and as a consequence there is a binning problem (in other words, it's hard to put it in nice squares). The newer version of smudgeplot (0.4.0 Arched) does not do any binning and plots everything as is - if you posted that plot, you might get a much clearer image.

From both the smudgeplot (despite the mess) and genomescope I can already tell these are high-ploids and nice ones too (not too degenerated, something young).

K

**Comment by vincianem** [comment]
Hi @KamilSJaron,

Thanks a lot for your answer! Alright, I've requested an update of the Smudgplot module on our cluster and will rerun the analysis with the newer version.

The problem with not getting the .smu files is not resolved. I would be very grateful to get any advise on that, especially because we lack flow cytometry measurements for these samples.

Best wishes,
Vinciane

**Comment by KamilSJaron** [comment]
Gene is looking into the problem, he will keep us posted. You are a second person that has seen it, and we have a reproducible example, so I am sure we (Gene) will figure it out

**Comment by vincianem** [comment]
Hi @KamilSJaron,

I redid the analysis with the newer version of smudgeplot (0.4.0 Arched) and it solved the case of _Salix caesia_, recovering all of them as tetraploid including 26M1. 

Here is the plot: 
[26M1.smudgeplot_smudgeplot_log10.pdf](https://github.com/user-attachments/files/18184359/26M1.smudgeplot_smudgeplot_log10.pdf)

With the newest version the .smu files of the three samples of _Salix polaris_ (467, EB30, EB31); for which I had issue were written. All these samples were expected to be hexaploid based on flow cytometry measurement of samples from the same population, but I would say that EB31 is rather tetraploid and I am unsure how to interpret EB30 results. May I ask your opinion?

**Comment by KamilSJaron** [comment]
Hi Vinciane, sorry for the delay, I tried to take the christmas break seriously :-)

26M1 looks very nice - that's as good as it can get I would say (notice the striking difference to the previous versions!!! Low coverage datasets looks so much better.) - to me that's most certainly non-hexapod. The coverage ratios are nowhere near 1/3 or 1/6 for any of the brigt smudges (which what you would expect for a hexaploid). There is a (rather unlikely) the species is a completely homozygous oktoploid (that would generate exactly the same signal, but very high-ploids are practically never homozygous; homozygous here I mean homozygous within subgenomes which again is just a mental gymnastics that I have seen only once or twice in 1000+ plots I have seen).

EB30 looks much more like a hexaploid if the coverage is estimated wrong - imagine it's actually 9x, not 18, then there would be a very strong AAAABB smudge and given a bit funny alignments of the smudges, I would not even be surprised if that's the case. And the problem is likely that you have an error filter somewhere close to that value which might kicks out most of the single copy k-mers in the dataset. I would look at k-mer histogram (genomescope) to get a feeling for 1n coverage.

For others it's hard to debug. What do you mean QC looks ok? If you would make genomescope plots for them all, that would make it a lot easier (you can immediately see if you have enough coverage by checking if there are any peaks in the spectra)....

FYI, you can get the k-mer spectrum directly from FastK k-mer database you needed for smudgeplot by running

```
Histex -G <path>/FastK_Table > <sample>.hist
```

Then you can upload `<sample>.hist` to http://genomescope.org/genomescope2.0/ and get the plots right away.

**Comment by KamilSJaron** [comment]
Hi @vincianem - would you mind if I would use your willow case and an example of a major difference between the old and new version of smugeplot at PopGroup58?

I plan to do nothing else than show the plot, give my interpretation while pointing out how much more one can see in the newer version.

**Comment by vincianem** [comment]
Hi @KamilSJaron,

My apologize for the late reply, I just got back to work ^^'.

Sure, feel free to use my willow case as an example :)!

**Comment by KamilSJaron** [comment]
Great :-) 

<img width="1512" alt="Screenshot 2025-01-08 at 14 23 39" src="https://github.com/user-attachments/assets/10963e75-ec93-4a73-bcfc-4e5e89214586" />

**Comment by vincianem** [comment]
Regarding the samples EB30, 467, 548 and 472, I did plot the k-mer histogram with genomescope to get an idea of the 1n coverage, but I most likely wrongly interpreted it. 

Here are the k-mer histograms: 
![467 genomescope_transformed_linear_plot](https://github.com/user-attachments/assets/d0995a31-cc6c-49d4-adee-22c5f872acc2)
![472 genomescope_transformed_linear_plot](https://github.com/user-attachments/assets/056d8df9-9747-40c1-81dd-3b1af25be22e)
![548 genomescope_transformed_linear_plot](https://github.com/user-attachments/assets/f919f2b1-531d-4ce4-b402-8cc65874118a)
![EB30 genomescope_transformed_linear_plot](https://github.com/user-attachments/assets/5c85e95b-b202-4383-a828-7c0ece23b1b1)

On EB30 plot the ploidy is written 4, it is a mistake in my script. It should be 6.

Would you have any suggestion based on the genomoscope plots?

**Comment by KamilSJaron** [comment]
Oh wow, those actually look quite reasonable and we might be able to get more reasonable smudgeplots... What L did you use originally? If it's like 4, it would explain a lot..

I am not sure what is going on with your sequencing runs, but there seems to be... quite a lot of mess, the errors are quite thick and sort of pour into the genomic peaks, which makes all the profiling work a bit messy. (and now I vaguely recall that willows are actually hard to sequence, but maybe I am just making stuff up now, it's just a vague recollection). Anyway, what you want is to pick L, so it kick off most of the errors, while keeping most of the genomic k-mers, and for some at least some that would be in a single copy (i.e. you really want at least part of that first peak).

So I would redo the smudgeplots with L a bit greater... like 15, 15 and 10 maybe? You lost some genomic k-mers but it might do the trick.

WHat I think is happening now is that you have so many errors in the set of k-mers that is enquired for the k-mer pairs that vast vast majority of pairs found are error and something else (either a different error or a genomic k-mer), those would create these "tide" pattern you shown.

I really hope this will fix it, because getting these smudgeplots done well would be very satifying.

**Comment by vincianem** [comment]
Hi @KamilSJaron,

Thanks a lot for your answer! I used L = 10 for all samples. 

Based on the fastq reports the raw data were fine. Here, I used the trimmed data (trimmed with fastp). I'll have to investigate for potential mess in the data. Maybe some contamination? From my experience, it can be tricky to get good DNA, but sequencing has not given us too much trouble. However, it is the first time we sequence _Salix_ polyploids.

I'll run smudgeplot again with L15 and L20, and I'll share the results. Indeed, it would be very satisfying to get these smudgeplots done :)

**Comment by KamilSJaron** [comment]
> Based on the fastq reports the raw data were fine. 

These reports are not really the most reliable thing to look at. The histograms are a lot more genuine (if you see peaks, you usually have a good chance of getting something out of it. More separation there is between peaks, easier everything gets).

> L = 10

THat is a bit of bad news, given the spectra, I would expect to see nice smudges already - that is very confusing, are you sure that you use the same k-mer database for the smudgeplot and genomescope? I would not bother L=20 that will cut too much into peaks L=15 might help, but I am a bit sceptical as this point. There IS something fishy about the genomescope / smudgpelot disagreements, i have never seen okeish spectra that would give no smudges at all.

**Comment by vincianem** [comment]
Only increasing L to 15 did not helped. However, there were two parameters I had completely overlooked; min_cov and max_cov. The default for the max coverage is 50 but according to the genomescope plots the max coverage is much higher, right? 

I set the max coverage at 150 for 467, 472, and EB30, and 80 for 548, and I am playing with different value of L. (5, 10, 15). I used 5 for 548 for example because on the genomescope plot kcov=~10. Does it make sense?

**Comment by vincianem** [comment]
I have a naive question: How do you interpret / use the centrality plot?

**Comment by vincianem** [comment]
I get a smudgeplot for 548 with the following parameters: L=5, min_cov=15 and max_cov=80. 
[548.5.15.80.smudgeplot_smudgeplot_log10.pdf](https://github.com/user-attachments/files/18414704/548.5.15.80.smudgeplot_smudgeplot_log10.pdf)

This sample is diploid according to flow cytometry, and I would interpret the smudgeplot as diploid. However, the error rate is quite high. Does it make sense?

**Comment by KamilSJaron** [comment]
> Only increasing L to 15 did not helped. However, there were two parameters I had completely overlooked; min_cov and max_cov. The default for the max coverage is 50 but according to the genomescope plots the max coverage is much higher, right?
> 
> I set the max coverage at 150 for 467, 472, and EB30, and 80 for 548, and I am playing with different value of L. (5, 10, 15). I used 5 for 548 for example because on the genomescope plot kcov=~10. Does it make sense?

I doesn't - max_cov is the maximal coverage that will be considered as potential 1n coverage (you need to make it higher only for high coverage genomes).

The centrality plot is giving you an idea how the 1n coverage fit went. This is not a naive question, this is not a very well documented process, because we are still working on improving it (it's much better than what we used to have, but I hope we can improve it even more).

One last question - how closely related these are? Given you have one that has the profiling alright you could also try to look at 2d k-mer spectra (KAT does that), which could help figuring out what's going on with these samples...

Alternatively, proceed with your study knowing there is something messy with these samples and that you might want to be more cautious about mapping rates, quality of called variants and things like that... I am afraid you are hitting the limit of how much you can figure out from profiling - there IS some funkiness, we just don't know what it is.

**Comment by KamilSJaron** [comment]
If anything, feel free to reopen
