### ISSUE TITLE
error with smudgeplot.py plot

### ISSUE THREAD

**Issue by smallfishcui** [KamilSJaron/smudgeplot#55]
Hi,
 
I installed smudgeplot and KMC using conda, and everything seems to look fine until I run the plot, then I get the message like this 

```
######################
## INPUT PROCESSING ##
######################
Error in if (round(peak_frame_4$cov[1]/peak_frame_2$cov[1]) >= 2) { : 
  missing value where TRUE/FALSE needed
Calls: estimate_1n_coverage_1d_subsets
Execution halted
```

Here is my code:

```
mkdir tmp
kmc -k25 -t4 -m16 -ci1 -cs10000 A10.1.fq.gz kmer_counts tmp
kmc -k25 -t4 -m16 -ci1 -cs10000 A10.2.fq.gz kmer_counts tmp
kmc_tools transform kmer_counts histogram kmer_k25.hist -cx10000
L=$(smudgeplot.py cutoff kmer_k25.hist L) #result 110
U=$(smudgeplot.py cutoff kmer_k25.hist U) #result 230
echo $L $U 
kmc_tools transform kmer_counts -ci$L -cx$U reduce kmer_counts_L$L\_U$U
kmc_tools transform kmer_counts -ci$L -cx$U dump -s kmer_counts_L$L\_U$U.dump
smudgeplot.py hetkmers -o kmer_pairs_L$L\_U$U < kmer_counts_L$L\_U$U.dump
smudgeplot.py plot kmer_pairs_L$L\_U$U\_coverages.tsv
```

What could be my problem? Is it because i used the kmc instead of  tbenavi1 /
KMC ? But in theory it is supposed to work, right?

Thanks,
Cui

**Comment by KamilSJaron** [comment]
Hi Cui, that seems like the R code found something unexpected in the kmer pairs file.

Namely, it seems that are not kmers found in four copies and smudgeplot does not like it. Would you mind sharing me the `kmer_pairs_L$L_U$U_coverages.tsv` file?

P.S. unrelated to smudgeplot. In bash you should to put quotes ("") around variables if you want them to be called correctly. LIke this:

```
smudgeplot.py hetkmers -o kmer_pairs_L"$L"_U"$U" < kmer_counts_L$L_U$U.dump
smudgeplot.py plot kmer_pairs_L"$L"_U"$U"_coverages.tsv
```

That won't resolve your issue though, just make nicer file names :-)

**Comment by KamilSJaron** [comment]
Sorry @smallfishcui, I don't see the attached file, could you perhaps send it to my email (kamiljaron at gmail)?

Yeah, I have seen a RAD smudgeplot before. It did not work well, because the number of loci sampled is usually not sufficient to fill the 2d histogram, I am suspecting this will be also the problem for you. However, the plot should be produced regardless, so I would still like to fix the issue.

For ddRAD I would suggest nQuire as a more suitable approach.

K

**Comment by smallfishcui** [comment]
Hi Kamil,

I sent to your email now. Please check if it arrives.

Best,
Cui

Kamil S. Jaron <notifications@github.com> 于2020年6月11日周四 下午2:57写道：

**Comment by KamilSJaron** [comment]
I resolved the problem in a very very hacky way and therefore I am hesitant to push it to master. (I shared the solution with @smallfishcui  via email).

The problem was in the way the kmer pairs file was constructed (there were no kmer pairs with minor allele coverage ratio smaller than 0.2 or so, which caused the algorithm to fail due to empty tables). Therefore I don't expect this to be frequent problem, but we should maybe do something about it at some point.

**Comment by heatherturtle** [comment]
Hi Kamil,
I started a new issue with something unrelated, however, I installed smudgeplot on my local disk and tried running a tsv file there.  I did not get the R issue, but I am getting this as error as a result! Side note --I am trying to estimate ploidy on GBS data, which is basically the same as RADseq. I took a screenshot of the tsv file. If you would like, I can send you a tsv file via email as tsv is unsupported on this platform.
![Screen Shot 2020-07-13 at 6 11 24 PM](https://user-images.githubusercontent.com/53024233/87362447-4d0eac80-c534-11ea-8dc7-48593821de93.png)

**Comment by KamilSJaron** [comment]
Hello, this page supports compressed files and I did not get the email, did you send it to my gmail? I checked my spam too, I don't see it.

I am happy to plot it for you, but I don't think it will look nice.  In [this wiki page](https://github.com/KamilSJaron/smudgeplot/wiki/everything-about-input-data) we discuss how PCR makes it difficult. These subsampling techniques as RAD never yielded in any meaningful smudgeplots till now (not that many tried, but enough to make me a bit sceptical), I would recommend tools like nQuire that deal better with coverage variation (it it's more prone for reference alignment, which are usually not such a big deal in RAD, I don't know GBS).

**Comment by bdentinger** [comment]
Hi - I'm encountering the same problem as Cui. I'm attaching my coverages file here for inspection. This was generated from reads mapped to a reference. Is this error
[MV_L230_U540_coverages.tsv.zip](https://github.com/KamilSJaron/smudgeplot/files/5145513/MV_L230_U540_coverages.tsv.zip)
 due to my coverage being lower than the ~50x suggested?

**Comment by KamilSJaron** [comment]
Hi @bdentinger, this error is because your smallest coverage ratio is 230 / (230 + 540), which means that no kmer pairs have smaller coverage ratio than 0.298. We use those to guess some features about the genome, I made a hacky way to skip some of those steps if there is so much data missing, but I think better way is to drastically increase your U and problably lowering your L too.

I have no idea how deep sequencing you have, but pick U that is at least 10x higher than your haploid coverage. That should resolve the problem.

**Comment by bdentinger** [comment]
Thanks @KamilSJaron! That is very helpful.

**Comment by KamilSJaron** [comment]
re ddRAD: [This paper](https://academic.oup.com/aobpla/article/12/6/plaa053/5911202#218926692), is reporting a bunch of ddRAD datasets with reasonably-looking coverage ratio histograms (authors have chosen not to include whole smudgeplots). Honestly, I was very pleasantly surprised to see it works!

So now I wonder, @bdentinger, did you manage to get a nicer smudgeplot with a higher U?

**Comment by RNieuwenhuis** [comment]
Hi @KamilSJaron ,

I did run into this issue in a sample that has really high coverage. 

> Error in if (round(peak_frame_4$cov[1]/peak_frame_2$cov[1]) >= 2) { :
> missing value where TRUE/FALSE needed
> Calls: estimate_1n_coverage_1d_subsets
> Execution halted

The 1N coverage is ~433, the automatic L and U detection were set to L= ~210 and U= ~2240. 

Specifying L=40 and U=5000 or even U=8000 did not resolve the issue. 

I've tried using the commandline option -l -n and --nbins , however with no success. 

Could you please help me to obtain a smudgeplot?

**Comment by KamilSJaron** [comment]
What is that genome @RNieuwenhuis ?! :-D

But sure. Would you send me the coverage histogram and coverage pairs file to my gmail? It's kamiljaron at gmail dot com.

**Comment by bdentinger** [comment]
Hi @KamilSJaron,

Sorry for the slow reply. I had really low (<2x) coverage and the higher U did not help. But I now have much higher coverage (>30x) so will try again and let you know if it still throws and error.

Cheers,

Bryn Dentinger
Curator of Mycology & Associate Professor of Biology
Natural History Museum of Utah (UMNH)
301 Wakara Way
Salt Lake City, UT 84108
Museum Office: 801-587-5741
Lab: 801-587-5729
Biology Office (LS207): 801-213-3695

dentingerlab.org
@NHMUMycology
dikaryon.wordpress.com
mycoilluminati.com

**Comment by RNieuwenhuis** [comment]
> 
> 
> What is that genome @RNieuwenhuis ?! :-D
> 
> But sure. Would you send me the coverage histogram and kmer pair coverages file to my gmail? It's kamiljaron at gmail dot com.

Hi Kamil, 

Thanks for your reply. I did send you the email, can you confirm that you received the email? It might have ended in your spamfilter because there is a downloadlink from our filesender in it. The downloadlink expires after a while. 

Looking forward to hear from you.

Best regards,

Ronald

**Comment by sivico26** [comment]
Hi @KamilSJaron,

Just wanted to pass and let you know that I ran into the same error mentioned in the first comment. In my case, I got a mistake calculating L and U and both got the value of 1, which made `*_coverages.tsv` a 2 columns matrix full of ones, and this caused the error when I tried to make the plot.

It is a minor thing, but I think it would be useful if the error message pointed out to check the `*_coverages.tsv` file.

Regards,
Sivico

**Comment by KamilSJaron** [comment]
Alright, those smudgeplot won't be nice, but I integrated my patchy solution... because it works! This bug should not appear with the new version, so if you will spot it again, let me know.

Of course using a version after ccc97a54a85201e482ec551262de4f43ed40c19e (the new release 0.2.5)
